# =====================================================================
# cloud-order 私有配置（group: DEFAULT_GROUP, namespace: public）
# =====================================================================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/cloud_order?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

# Feign 调试日志
logging:
  level:
    com.cloud.order.feign: debug
